config/routes.rb
Rails.application.routes.draw do

  resources :wikis

  resources :collaborators, only: [:create, :destroy]

  resources :charges, only: [:new, :create]

  devise_for :users

  get 'welcome/index'

  get 'welcome/about'

  post 'charges/downgrade' => 'charges#downgrade', :as => 'downgrade_user'

  root to:'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki

  def self.available(wiki, current_user)
    # Anyone who is not the wiki owner, generates an array
    possible_collaborators = User.all.where.not(id: current_user.id)
    # Does this wiki already have collaborators
    already_taken = wiki.collaborators.map { |collaborator| User.find_by_id(collaborator.user_id) }
    possible_collaborators - already_taken
    # leave us with an array with the possible collaborators
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :wikis, dependent: :destroy
  has_many :collaborators
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role:[:standard, :premium, :admin]
  after_initialize {self.role ||= :standard}

  def downgrade
  	self.update_attribute(:role, 'standard')
  end

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  private

  def user_not_authorized
    flash[:alert] = "Access denied"
    redirect_to (request.referrer || root_path)	
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def create
  # Creates a Stripe Customer object, for associating
  # with the charge
    
  	customer = Stripe::Customer.create(
    	email: current_user.email,
    	card: params[:stripeToken]
  	)
 
  # Where the real magic happens

  	Stripe::Charge.create(
      customer: customer.id,
      amount: 15_00,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

  	current_user.update_attribute(:role, 'premium')
 
  	flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
  	redirect_to wikis_path(current_user) # or wherever
 
  # Stripe will send back CardErrors, with friendly messages
  # when something goes wrong.
  # This `rescue block` catches and displays those errors.
  	rescue Stripe::CardError => e
    	flash[:alert] = e.message
    	redirect_to new_charge_path
	end

	def new
  	@stripe_btn_data = {
    	key: "#{ Rails.configuration.stripe[:publishable_key] }",
    	description: "Premium Membership - #{current_user}",
    	amount: 15_00
  	}
	end

	def downgrade
		@user = current_user
		@user.downgrade
    @wikis = @user.wikis
		flash[:notice] = "Bye #{current_user.email}!"
    @wikis.each do |wiki|
      if wiki.private == true
        wiki.update_attributes!(private: false)
      end
    end  
		redirect_to root_path
	end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create

  	@collaboration = Collaborator.new(collaborators_params)

  	if @collaboration.save
  		flash[:notice] = "User is a collaborator."
      redirect_to @collaboration.wiki
    else
      flash[:alert] = "Error adding the user. Please try again."
      redirect_to Wiki.find_by(params[:collaborator][:wiki_id])
    end
  end

  def destroy

  	@collaboration = Collaborator.find(params[:id])

  	if @collaboration.destroy
      flash[:notice] = "User has been deleted"
      redirect_to @collaboration.wiki
    else
      flash[:alert] = "There was an error deleteing the user."
      redirect_to @collaboration.wiki
    end
  end

  private

  def collaborators_params
  	params.require(:collaborator).permit(:wiki_id, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  before_action :authenticate_user!


  def index
  end

  def about
  end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController

  def index
  	@wiki = Wiki.all
  end

  def new
   	@wiki = Wiki.new
  end

  def show
    @wiki = Wiki.find(params[:id])
  end
 
  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
   	if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

private

  def wiki_params
    params.require(:wiki).permit(:title, :body)
  end  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def new
   	@wiki = Wiki.new
    authorize @wiki
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    authorize @wiki

    @wiki.user = current_user

   	if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @all_collaborators = Collaborator.available(@wiki, current_user)
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	 def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Montythemoose</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", welcome_index_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <li><%= link_to "Wikis", wikis_path %></li>
           <% if user_signed_in? %>
            <li>
              <li class="pull-right"><%= link_to(current_user.email, edit_user_registration_path)%></li>
              <li class="pull-right"><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %>        
            </li>
          <% else %>
            <li>
              <li class="pull-right"><%= link_to('Sign In', new_user_session_path)  %>  
            </li>
          <% end %>
        </ul>
        <div>
      <% if flash[:notice] %>
        <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
        </div>
        <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
        </div>
        <% elsif flash[:alert] %>
        <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
        </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome Wiki Fans</h1>
<p>Welcome to my wikis page. Feel free to make some wikis.</p>

<ul class="nav nav-tabs">
	<li><%= link_to "Downgrade", downgrade_user_path, method: :post, class: "btn btn-danger center-block", data: {confirm: "Are you sure you want to downgrade your account? All your private wikis will be made public!"} %></li>
</ul>

app/views/wiki/show.html.erb
<h1><%= @pwiki.title %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @wiki.body %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%= link_to "Delete Post", @wiki method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
   </div>
 </div>

app/views/wikis/_dropdown.html.erb
<%= form_for Collaborator.new do |f| %>
  <%= f.label :add_collaborators, :style => "margin-top: 10px; font-size: 17px" %><br>
  <%= f.select(:user_id, @all_collaborators.collect {|w| [w.email, w.id]}, :prompt => 'Select a collaborator', :style => "width: 20px") %><br>
  <%= f.hidden_field :wiki_id, value: @wiki.id %><br>
  <%= f.submit "Add", class: 'btn btn-success btn-sm'%>
<% end %>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  
  <div class="form-group">
    <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% if current_user.premium? || current_user.admin? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki} %>
   </div>
  <div class="col-md-8">
    <%= render partial: 'dropdown'%>
   </div>
   <% @wiki.collaborators.each do |collaborator| %>
     <%= collaborator.user.email %>
     <%= link_to 'Remove', collaborator_path(collaborator), data: { confirm: 'Are you sure?' }, :style => "margin-left: 40px", method: :delete %>
   <% end %>
 </div>

app/views/wikis/index.html.erb
<h1>All Wiki Posts</h1>
 <% @wikis.each do |wiki| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>

 <% end %>
 <div class="col-md-4">
 	<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
 </div>

app/views/wikis/new.html.erb
 <h1>New Wiki Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wiki</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki} %>
   </div>
 </div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>